version: "3.9"

services:
  app:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - mysql
    volumes:
      - ./configs/docker.env:/app/configs/.env
      - logs:/app/logs:rw

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tidyhunter1
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  loki:
    image: grafana/loki:2.9.0
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - logs:/var/log:rw
      - ./infrastructure/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafanadata:/var/lib/grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000

volumes:
  mysqldata:
  grafanadata:
  logs:
