// errorCodes.js
const AT_LEAST_ONE_UPDATE_REQUIRED_CODE = 0;
const INVALID_STATUS_CODE = 1;
const INVALID_STATUS_TRANSITION_CODE = 2;
const TASK_NOT_FOUND_CODE = 3;
const CONCURRENCY_ERROR_CODE = 4;

module.exports = {
  AT_LEAST_ONE_UPDATE_REQUIRED_CODE,
  INVALID_STATUS_CODE,
  INVALID_STATUS_TRANSITION_CODE,
  TASK_NOT_FOUND_CODE,
  CONCURRENCY_ERROR_CODE,
};
